name: Interoperability solution
description: This form can be used to add a new service to the IF solutions list.
title: "[IF Solution]: "
labels: ["if_solution"]
body:
  - type: markdown
    attributes:
      value: |
        Introduction to the form...
  - type: dropdown
    id: problem_id
    attributes:
      label: Problem ID this solutions adresses
      description: 
      options:
        - S1
        - S2
    validations:
      required: true    
  - type: input
    id: name
    attributes:
      label: Name of the solution (IF solution) 
      description: 
      placeholder: ex. service X
    validations:
      required: true
  - type: textarea
    id: problems_solved
    attributes:
      label: Problems that CAN be solved with this IF solution
      description: 
      placeholder: 
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Description of IF solution
      description: 
      placeholder: 
    validations:
      required: false      
  - type: dropdown
    id: status
    attributes:
      label: Status
      description: 
      options:
        - In development
        - Ready
    validations:
      required: true         
  - type: textarea
    id: limitations
    attributes:
      label: Limitations of this IF solution
      description: 
      placeholder: 
    validations:
      required: false
  - type: dropdown
    id: type
    attributes:
      label: Type of the IF solution
      description: 
      options:
        - Guidelines
    validations:
      required: true     
  - type: textarea
    id: usecases
    attributes:
      label: Description of use case/scenario/case of study for this IF solution
      description: 
      placeholder: 
    validations:
      required: false     
  - type: input
    id: link
    attributes:
      label: Link to documentation (URL)
      description: 
    validations:
      required: false                    
  - type: textarea
    id: parties
    attributes:
      label: EOSC project/initiative, that is working on the solution
      description: 
      placeholder: 
    validations:
      required: false        
  - type: textarea
    id: comments
    attributes:
      label: Other comments
      description: 
      placeholder: 
    validations:
      required: false
